askbotmini/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('askbotmini.views',
            url(r'^$', 'index', name='askbot-index'),            
            url(r'^questions/ask/$', 'ask_question', name='ask-question'),
            url(r'^questions/(?P<id>\d+)/$', 'view_question', name='view-question'),
            url(r'^questions/(?P<id>\d+)/edit/$', 'edit_question', name='edit-question'),
            url(r'^questions/(?P<question_id>\d+)/delete/$', 'delete_question', name='delete-question'),
            url(r'^posts/(?P<id>\d+)/edit/$', 'edit_answer', name='edit-answer'),
            url(r'^tagged/(?P<tag_name>\w+)/$', 'tagged_in', name='tagged-in'),
)

sitio/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView
from models import *

urlpatterns = patterns('sitio.views',
			#url(r'^$', ListView.as_view(model=Videos,
			#							template_name="videos/video_list.html"
			#							),name="lista-videos"),
			#url(r'^(?P<slug>[-\w]+)/$', DetailView.as_view(model=Videos,
			#											   template_name="videos/video_detail.html"
			#											   ),name="detalle-videos"),
			url(r'^(?P<slug>[-\w]+)/$', 'detalle', name="detalle-videos"),
			
			
                

    )

sitioweb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from settings import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sitioweb.views.home', name='home'),
    # url(r'^sitioweb/', include('sitioweb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^$', 'sitio.views.index'),
    url(r'^poner_en_vivo/$', 'sitio.views.ponerEnVivo'),
    url(r'^vivoTemplate/$', 'sitio.views.vivoTemplate'),
    url(r'^sitio/', include('sitio.urls')),
    url(r'^foro/', include('askbotmini.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),
    url(r'^comunidades/', 'sitio.views.comunidades'),

)

handler404 = 'sitioweb.views.file_not_found_404'

handler500 = 'sitioweb.views.file_not_found_500'

urlpatterns += staticfiles_urlpatterns()

if DEBUG:
    urlpatterns += patterns('',
                (r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
                )

askbotmini/models.py
# -*- coding: UTF-8 -*-
from django.contrib.auth.models import User
from tagging.models import Tag
from tagging_autocomplete.models import TagAutocompleteField
from south.modelsinspector import add_introspection_rules
from django.db import models

import datetime
#add_introspection_rules([], ["^tagging_autocomplete\.models\.TagAutocompleteField"])


class Question(models.Model):
    question = models.CharField(max_length=300, verbose_name='Titulo')
    description = models.TextField()
    date_created = models.DateTimeField(default=datetime.datetime.now())
    tags = TagAutocompleteField(verbose_name='Palabras Claves',help_text='Separar elementos con "," ')
    last_answer_date = models.DateTimeField(default=datetime.datetime.now())
    views = models.IntegerField()
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s' % self.question

    class Meta:
        verbose_name = u'Pregunta'
        verbose_name_plural = u'Preguntas'

    #Para jalar las tags
    def set_tags(self, tags):
        Tag.objects.update_tags(self, tags)

    def get_tags(self):
        return Tag.objects.get_for_object(self)

    def get_answer_count(self):
        if self.answer_set.all().count() == 0:
            return 0        
        return self.answer_set.all().count()

    def last_answer(self):
        return self.answer_set.latest('fecha')


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer = models.TextField()
    fecha = models.DateTimeField(datetime.datetime.now())
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s' % self.question
    
    class Meta:
        ordering = ['fecha', ]
        verbose_name = u'Respuesta'
        verbose_name_plural = u'Respuestas'

    def save(self, force_insert=False, force_update=False):
        self.question.last_answer_date = self.fecha
        self.question.save()
	super(Answer, self).save(force_insert, force_update)

class View(models.Model):
    question = models.ForeignKey(Question)
    ip = models.CharField(max_length=40)

    def __unicode__(self):
        return u'%s - %s' % (self.ip, self.question)

    class Meta:
        verbose_name = 'View'
        verbose_name_plural = 'Views'

askbotmini/forms.py
from django import forms
from tagging.forms import TagField
from tagging_autocomplete.widgets import TagAutocomplete
from models import *

class AskForm(forms.ModelForm):
    tags = TagField(widget=TagAutocomplete())
    notify = forms.BooleanField(required=False)

    class Meta:
        model = Question
        exclude = ['date_created', 'views', 'user', 'last_answer_date']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ['question', 'user', 'fecha']

askbotmini/views.py
import operator
import thread
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.core.mail import send_mail
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from askbotmini.forms import AskForm, AnswerForm
from askbotmini.models import Question, Answer, View
from tagging.models import Tag
from tagging.models import TaggedItem
from django.contrib.sites.models import Site

def index(request):
    request.session['flag'] = 'foro'
    barra_foro = 'index'
    questions = Question.objects.all().order_by('-last_answer_date')

    #valorando si muestra solo las ultimas preguntas
    tab = request.GET.get('tab', '')
    if tab == 'latest':
        barra_foro = 'latest'
        questions = Question.objects.all().order_by('-date_created')

    tags = Tag.objects.usage_for_model(Question, counts=True)
    tags.sort(key=operator.attrgetter('count'), reverse=True)  

    query = request.GET.get('q', '')
    if query:
        result_questions = Question.objects.filter(question__icontains=query)
        result_tags = Tag.objects.filter(name__icontains=query)
        lista = []
        tags = []
        for n in result_questions:
            lista.append(n)
        for rtag in result_tags:
            TaggedItems = TaggedItem.objects.get_by_model(Question, rtag.name)
            if not rtag.items.all().count() == 0:
                li = []
                for it in rtag.items.all():
                    if it.object:
                        li.append(it)
                tags.append({'name':rtag.name, 'count': len(li)})
            for item in TaggedItems:
                lista.append(item)
        tags.sort(key=operator.itemgetter('count'), reverse=True)
        questions = list(set(lista))        

    return render_to_response('askbotmini/index.html', locals(), context_instance=RequestContext(request))

@login_required
def ask_question(request):
    if request.method == 'POST':
        form = AskForm(request.POST)
        if form.is_valid():
            obj = Question()
            obj.question = request.POST['question']
            obj.description = request.POST['description']
            obj.user = request.user
            obj.views = 0
            obj.date_created = datetime.datetime.now()
            obj.tags = request.POST['tags']
            obj.save()
            if form.cleaned_data['notify']:
                thread.start_new_thread(notify_all, (obj,))
            return HttpResponseRedirect('/foro/?tab=latest')
    else:
        form = AskForm()
    return render_to_response('askbotmini/ask_question.html', 
                              RequestContext(request, locals()))

@login_required
def edit_question(request, id):
    question = get_object_or_404(Question, id=int(id))    
    if not question.user == request.user:
        return HttpResponse('<h1>Permiso denegado</h1>')

    if request.method == 'POST':
        form = AskForm(request.POST)
        if form.is_valid():            
            question.question = request.POST['question']
            question.description = request.POST['description']
            question.tags = request.POST['tags']
            question.save()
            return HttpResponseRedirect('/foro/questions/%s' % question.id)
    else:
        form = AskForm(instance=question)
    return render_to_response('askbotmini/ask_question.html', 
                              RequestContext(request, locals()))

@login_required
def view_question(request, id):
    tags = Tag.objects.usage_for_model(Question, counts=True)
    tags.sort(key=operator.attrgetter('count'), reverse=True)
    question = get_object_or_404(Question, id=int(id))
    user_ip = request.META['REMOTE_ADDR']

    try:
        vista = View.objects.get(question=question, ip=user_ip)
    except:
        vista = View()
        vista.question = question
        vista.ip = user_ip
        vista.save()
        question.views = question.views + 1
        question.save()

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = Answer()
            answer.question = question
            answer.answer = form.cleaned_data['answer']
            answer.fecha = datetime.datetime.now()
            answer.user = request.user
            answer.save()
            #notify_user(question, answer)
            thread.start_new_thread(notify_user, (question, answer))
            return HttpResponseRedirect('/foro/questions/%s/?ansid=%s' % (question.id, answer.id))
    else:
        form = AnswerForm()

    ansid = request.GET.get('ansid', '')

    return render_to_response('askbotmini/view_question.html', RequestContext(request, locals()))

@login_required
def edit_answer(request, id):
    tags = Tag.objects.usage_for_model(Question, counts=True)
    tags.sort(key=operator.attrgetter('count'), reverse=True)
    answer = get_object_or_404(Answer, id=id)

    if answer.user != request.user:
        return HttpResponse('<h2>Acceso Denegado</h2>')

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/foro/questions/%s/?ansid=%s' % (answer.question.id, answer.id))
    else:
        form = AnswerForm(instance=answer)

    return render_to_response('askbotmini/edit_answer.html', RequestContext(request, locals()))

@login_required
def tagged_in(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    questions = TaggedItem.objects.get_by_model(Question, tag.name).order_by('-last_answer_date')

    tags = Tag.objects.usage_for_model(Question, counts=True)
    tags.sort(key=operator.attrgetter('count'), reverse=True)
    return render_to_response('askbotmini/tagged_in.html', RequestContext(request, locals()))

#este sera el hilo para mandar mails
def notify_all(question):
    site = Site.objects.get_current()
    users = User.objects.all().exclude(username='admin').exclude(username=question.user.username)
    contenido = render_to_string('askbotmini/notify_new_question.txt', {'question': question,
                                 'url': '%s/foro/questions/%s' % (site, question.id),
                                 'url_answer': '%s%s/#answer' % (site, question.id),
                                 })
    for user in users:
        if user.email:
            send_mail('Nueva pregunta', contenido, 'develop@simasni.org', [user.email, ])

def notify_user(question, answer):
    site = Site.objects.get_current()
    
    text_content = render_to_string('askbotmini/notify_new_answer_text.txt', {'question': question,
                                 'url': '%s%s' % (site, question.id),
                                 'url_answer': '%s/foro/questions/#%s' % (site, answer.id),
                                 'answer': answer
                                 })
    html_content = render_to_string('askbotmini/notify_new_answer.txt', {'question': question,                                 
                                 'url_answer': '%s%s/?ansid=%s' % (site, question.id, answer.id),
                                 'answer': answer
                                 })

    msg = EmailMultiAlternatives('1 Pregunta tiene 1 Respuesta nueva', text_content, 'develop@simasni.org', [question.user.email, ])
    msg.attach_alternative(html_content, "text/html")
    msg.send()  

@login_required
def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if question.user == request.user or request.user.is_superuser:
        question.delete()
        return redirect('askbot-index')
    else:
        return redirect('view-question', question_id)

askbotmini/templates/askbotmini/ask_question.html
{% extends "baseforo.html" %}
{% block extra_header %}
<link href="{{MEDIA_URL}}css/askbotmini.css" rel="stylesheet" type="text/css">
<link href="{{MEDIA_URL}}css/jquery.autocomplete.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/files/js/autocomplete/jquery.autocomplete.js"></script>
<script type="text/javascript" src="/files/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/files/js/tiny_mce/askbotconfig.js"></script>
{% endblock %}
{% block contenido %}
<div id="sidebar">
    {% include "askbotmini/sidebar.html" %}
</div> 
<div id="contenido">
 <div id="encabezado_contenido">Foro de Discuciones</div>
<div>
    <form action="." method="post">{% csrf_token %}
        <table class="askquestion">
            <tr>
                <td>
                    <label for="question"><b>{{form.question.label}}</b></label><br>
                    {{form.question}}
                </td>
            </tr>
            <tr>
                <td>{{form.description}}</td></tr>
            <tr>
                <td>
                    <label for="id_tags"><b>Tags:</b></label><br>
                    {{form.tags}}
                </td>
            </tr>
            <tr>               
                <td>
                    {{form.notify}}<label for="id_notify">Notificar a los usuarios del sitio</label>
                </td>                
            </tr>            
        </table>
        <input id="boton-preguntar" type="submit" value="Guardar">
    </form>
</div>


</div>
{% endblock %}

askbotmini/templates/askbotmini/edit_answer.html
{% extends "baseforo.html" %}
{% block extra_header %}
<style type="text/css">
    #id_answer{
        margin-left: 0px !important;
    }
</style>
{% endblock %}
{% block contenido %}
<div id="sidebar">
    {% include "askbotmini/sidebar.html" %}
</div>
<div id="contenido">
    <div id="encabezado_contenido">Foro de Discuciones</div>
    <div id="barra_foro">
        <a href="/foro/"><img src="/files/img/discucion.png" >Discuciones destacadas</a>
        <a href="/foro/?tab=latest"><img src="/files/img/ultimas.png" alt="ultimas noticias">Ultimas discuciones</a>
        <a href="/foro/questions/ask/" style="float:right;width:120px"><img src="/files/img/add.png" >Crear un foro</a>
    </div>
    <div class="question_list">
        <div id="question-detail">
            <div class="question">
                <div class="question_detail">
                    <div class="titulo-foro"><a href="">{{answer.question.question}}</a>
                        {{answer.question.description|safe}}
                    </div>
                    <div class="publicadop">
                        Publicado por: <a href="">{{answer.question.user}} </a>hace {{answer.question.date_created|timesince}}<br>
                    </div>

                    <div class="tags">{% for tag in answer.question.get_tags %}<a href="/foro/tagged/{{tag.name}}">{{tag.name}}</a>{% endfor %}</div>
                    <div class="clean"></div>
                </div>
            </div>
            <div class="respuestas-comment">
                <div class="num-respuesta-commnet left">Respuesta</div>
                <div class="clean"></div>
                <br>
                <div id="answer">                    
                    <div>
                        <form action="." method="POST">{% csrf_token %}
                            {{form.answer}}
                            <input id="boton-preguntar" type="submit" value="Responder">
                        </form>
                    </div>
                    <div class="clean"></div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

askbotmini/templates/askbotmini/index.html
{% extends "baseforo.html" %}
{% block title %}Foros{% endblock %}
{% block extra_header %}
{% endblock %}
{% block contenido %}

<div>
    {% include "askbotmini/sidebar.html" %}
</div>
<div class="span10 well">
    <div id="encabezado_contenido">Foro de Discuciones <div style="float:right; margin-right:5px;">{{questions.count}} Discusiones</div></div>
    <div id="barra_foro">
    
        <a href="/foro/" {% if barra_foro == 'index' %}class='selected'{% endif %}><img src="/files/img/destacado.png" alt="discusion" height="24" width="25" >Discusiones destacadas</a>
            
        <a href="/foro/?tab=latest"  {% if barra_foro == 'latest' %}class='selected'{% endif %}><img src="/files/img/visto.png" alt="destacadas" height="24" width="25">Ultimas discusiones</a>
            
        <a class="btn" href="/foro/questions/ask/" style="float:right;width:120px"><img src="/files/img/plus.png" alt="add foro" height="24" width="25"> Crear un foro</a>
    </div>

    <div class="question_list">
        {% for question in questions %}
        <div class="question">
            <div class="left">
                {%if question.answer_set.all.count == 0 %}
                    <div class="num_respuestas-red">{{question.answer_set.all.count}}</div>
                    <div class="respuestas-red">
                        RESPUESTAS
                    </div>
                {%else%}
                    <div class="num_respuestas">{{question.answer_set.all.count}}</div>
                    <div class="respuestas">
                        RESPUESTAS
                    </div>
                {%endif%}
            </div>
            <div class="left">
                <div class="num_clicks">{{question.views}}</div>
                <div class="clicks">VISTAS</div> 
            </div>
            <div class="titulo-foro"><a href="./questions/{{question.id}}/" title="{{question.question}}">{{question.question}}</a></div>

            <div class="tags">{% for tag in question.get_tags %}<a href="/foro/tagged/{{tag.name}}">{{tag.name}}</a>{% endfor %}</div>
            <div class="clean"></div>
            <div class="publicadop">
                {% if tab == 'latest' %}
                Creado hace {{question.date_created|timesince}}
                por <a href="">{{question.user}}</a>
                {% else %}
                {% if question.last_answer %}
                Respuesta hace {{question.last_answer.fecha|timesince}}
                por <a href="">{{question.last_answer.user}}</a>
                {% else %}
                Creado hace {{question.date_created|timesince}}
                por <a href="">{{question.user}}</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="clean"></div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

askbotmini/templates/askbotmini/sidebar.html
<!--Sidebar-->
<div class="span2">
<div class="well">
	<h2>Temas</h2>
	<ul class="pager">
	    {% for tag in tags %}
	    <li> <a href="/foro/tagged/{{tag.name}}">{{tag.name}}</a> {% if query %} x {{tag.count}}{% else %}{{tag.get_real_items}}{% endif %}<br><br></li>
	    {% endfor %}
	</ul>
</div>
</div>

askbotmini/templates/askbotmini/tagged_in.html
{% extends "baseforo.html" %}
{% block title %}Foros | {{tag.name}}{% endblock %}
{% block extra_header %}
{% endblock %}
{% block contenido %}
<div id="sidebar">
    {% include "askbotmini/sidebar.html" %}
</div> 
<div id="contenido">    
    <div id="encabezado_contenido">Foro de Discuciones <div style="float:right; margin-right:5px;">{{questions.count}} Discusiones</div></div>
    <div id="barra_foro">
        <a href="/foro/" {% if barra_foro == 'index' %}class='selected'{% endif %}><img src="/files/img/discucion.png" alt="discusion">Discusiones destacadas</a>
        <a href="/foro/?tab=latest"  {% if barra_foro == 'latest' %}class='selected'{% endif %}><img src="/files/img/ultimas.png" alt="destacadas">Ultimas discusiones</a>
        <a href="/foro/questions/ask/" style="float:right;width:120px"><img src="/files/img/add.png" alt="add foro">Crear un foro</a>
    </div>
    <div class="question_list">
        <div class="num-respuesta-commnet">Foros encontrados para tema > <b>{{tag.name}}</b></div>
 {% for question in questions %}
        <div class="question">
            <div class="left">
                {%if question.answer_set.all.count == 0 %}
                                <div class="num_respuestas-red">{{question.answer_set.all.count}}</div>
                <div class="respuestas-red">
                    RESPUESTAS
                </div>
                {%else%}
                <div class="num_respuestas">{{question.answer_set.all.count}}</div>
                <div class="respuestas">
                    RESPUESTAS
                </div>
                {%endif%}
            </div>
            <div class="left">
                <div class="num_clicks">{{question.views}}</div>
                <div class="clicks">VISTAS</div> 
            </div>
            <div class="titulo-foro"><a href="/foro/questions/{{question.id}}/" title="{{question.question}}">{{question.question}}</a></div>

            <div class="tags">{% for tag in question.get_tags %}<a href="/foro/tagged/{{tag.name}}">{{tag.name}}</a>{% endfor %}</div>
            <div class="clean"></div>
            <div class="publicadop">
                {% if tab == 'latest' %}
                Creado hace {{question.date_created|timesince}}
                por <a href="">{{question.user}}</a>
                {% else %}
                {% if question.last_answer %}
                Respuesta hace {{question.last_answer.fecha|timesince}}
                por <a href="">{{question.last_answer.user}}</a>
                {% else %}
                Creado hace {{question.date_created|timesince}}
                por <a href="">{{question.user}}</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="clean"></div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

askbotmini/templates/askbotmini/view_question.html
{% extends "baseforo.html" %}
{% block extra_header %}
<script src="/files/js/jquery.color.js"></script>
<script type="text/javascript">
    $(document).ready(function(){        
        if (window.location.href.indexOf('#answer')!=-1){                        
            answer();
        }
        {% if ansid %}
        $('html, body').animate({
            scrollTop: $('#answer-{{ansid}}').offset().top
        }, 500);
        $("#answer-{{ansid}}").animate( { backgroundColor: '#BEDA53' }, 10).animate( { backgroundColor: 'white' }, 2000);
        {% endif %}
    });
    function answer(){
        $('html, body').animate({
            scrollTop: $('#answer').offset().top
        }, 1000);        
        $("#answer").animate( { backgroundColor: '#BEDA53' }, 10)
        .animate( { backgroundColor: 'white' }, 2000);        
        window.location.href='#answer';
    }    
</script>
{% endblock %}
{% block contenido %}
<div id="sidebar">
    {% include "askbotmini/sidebar.html" %}
</div> 
<div class="span10">
    <div id="encabezado_contenido">Foro de Discuciones</div>
    <div id="barra_foro">
        <a href="/foro/"><img src="/files/img/discucion.png" >Discuciones destacadas</a>
        <a href="/foro/?tab=latest"><img src="/files/img/ultimas.png" >Ultimas discuciones</a>
        <a href="/foro/questions/ask/" style="float:right;width:120px"><img src="/files/img/add.png" >Crear un foro</a>
    </div>
    <div class="question_list">
        <div id="question-detail">
            <div class="question">
                <div class="question_detail">
                  <div class="titulo-foro"><a href="">{{question.question}}</a> {% if question.user == request.user or request.user.is_superuser %}| <a href="edit/">[editar]</a><a href="delete/">[borrar]</a>{% endif %}
                        {{question.description|safe}}
                    </div>
                    <div class="publicadop">
                        Publicado por: <a href="">{{question.user}} </a>hace {{question.date_created|timesince}}<br>
                    </div>

                    <div class="tags">{% for tag in question.get_tags %}<a href="/foro/tagged/{{tag.name}}">{{tag.name}}</a>{% endfor %}</div>
                    <div class="clean"></div>
                </div>
            </div>
            <div class="respuestas-comment">
                <div id="nueva-respuesta"><a onclick="answer(); $('#id_answer').focus();" href="javascript:void(0);"><img src="/files/img/forum/new_post.png">Contestar</a></div>
                <div class="num-respuesta-commnet left">{{question.answer_set.all.count}} Respuestas</div>
                <div class="clean"></div>
                {% for answer in question.answer_set.all %}
                <div class="comment" id="answer-{{answer.id}}">
                    <div class="publicadop" id="{{answer.id}}">
                        {% if answer.user == request.user %}
                        <a href="/foro/posts/{{answer.id}}/edit">[editar]</a> |
                        {% endif %}
                        <a href="#{{answer.id}}">{{answer.user}}</a> hace {{answer.fecha|timesince}} dijo:                        
                    </div><br>
                    {{answer.answer}}
                </div>
                <br>
                {% endfor %}
                <br>
                <div id="answer">
                    <div  class="num-respuesta-commnet left">RESPONDER</div><br><br>
                    <div>
                        <form action="." method="POST">{% csrf_token %}
                            {{form.answer}}
                            <input id="boton-preguntar" type="submit" value="Responder">
                        </form>
                    </div>
                    <div class="clean"></div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}